#!/bin/bash
# =============================================================================
# 01-os-tuning.sh - OS Tuning with Persistence
# =============================================================================
# Applies OS tuning settings and makes them PERSISTENT across reboots.
# This is critical for snapshot recovery scenarios.
#
# Persistence locations:
#   - sysctl: /etc/sysctl.d/99-postgres.conf
#   - ulimits: /etc/security/limits.d/99-postgres.conf
#   - hugepages: /etc/sysctl.d/99-hugepages.conf
#   - THP: systemd service
#
# Usage: sudo ./01-os-tuning.sh [config.env]
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/../config/os.env"

# Detect node type: DB node has RAID arrays or will have them
# Proxy node has neither and won't get PostgreSQL
IS_DB_NODE=false
DISK_COUNT=$(lsblk -d -n -o NAME | grep -v -E '^loop|^ram' | wc -l)
[[ $DISK_COUNT -gt 1 ]] || [[ -e /dev/md0 ]] || [[ -d /data/postgresql ]] && IS_DB_NODE=true

if [[ "$IS_DB_NODE" == "true" ]]; then
    echo "=== OS Tuning (DB Node - Full) ==="
else
    echo "=== OS Tuning (Proxy Node - TCP Only) ==="
fi

# Source config from standard location
if [[ -f "$CONFIG_FILE" ]]; then
    echo "Loading config from: $CONFIG_FILE"
    source "$CONFIG_FILE"
else
    echo "WARNING: Config file not found: $CONFIG_FILE (using defaults)"
fi

# =============================================================================
# SYSCTL - Memory & VM (DB node only) + Network (both)
# =============================================================================
if [[ "$IS_DB_NODE" == "true" ]]; then
    echo "[1/5] Configuring sysctl - Memory + Network (persistent)..."
    cat > /etc/sysctl.d/99-postgres.conf << EOF
# PostgreSQL Optimized Settings (DB Node)
# Generated by 01-os-tuning.sh - DO NOT EDIT MANUALLY

# === MEMORY ===
vm.swappiness = ${VM_SWAPPINESS:-1}
vm.dirty_background_ratio = ${VM_DIRTY_BACKGROUND_RATIO:-1}
vm.dirty_ratio = ${VM_DIRTY_RATIO:-4}
vm.dirty_expire_centisecs = ${VM_DIRTY_EXPIRE_CENTISECS:-200}
vm.dirty_writeback_centisecs = ${VM_DIRTY_WRITEBACK_CENTISECS:-100}
vm.overcommit_memory = ${VM_OVERCOMMIT_MEMORY:-2}
vm.overcommit_ratio = ${VM_OVERCOMMIT_RATIO:-80}
vm.min_free_kbytes = ${VM_MIN_FREE_KBYTES:-335544}
vm.zone_reclaim_mode = ${VM_ZONE_RECLAIM_MODE:-0}
vm.vfs_cache_pressure = ${VM_VFS_CACHE_PRESSURE:-100}

# === FILE DESCRIPTORS ===
fs.file-max = ${FS_FILE_MAX:-2097152}
fs.aio-max-nr = ${FS_AIO_MAX_NR:-1048576}

# === NETWORK ===
net.core.somaxconn = ${NET_CORE_SOMAXCONN:-4096}
net.core.netdev_max_backlog = ${NET_CORE_NETDEV_MAX_BACKLOG:-2048}
net.core.rmem_default = ${NET_CORE_RMEM_DEFAULT:-262144}
net.core.rmem_max = ${NET_CORE_RMEM_MAX:-16777216}
net.core.wmem_default = ${NET_CORE_WMEM_DEFAULT:-262144}
net.core.wmem_max = ${NET_CORE_WMEM_MAX:-16777216}
net.ipv4.tcp_rmem = ${NET_IPV4_TCP_RMEM:-4096 87380 16777216}
net.ipv4.tcp_wmem = ${NET_IPV4_TCP_WMEM:-4096 65536 16777216}
net.ipv4.tcp_max_syn_backlog = ${NET_IPV4_TCP_MAX_SYN_BACKLOG:-4096}
net.ipv4.tcp_tw_reuse = ${NET_IPV4_TCP_TW_REUSE:-1}
net.ipv4.tcp_fin_timeout = ${NET_IPV4_TCP_FIN_TIMEOUT:-15}

# === TCP KEEPALIVE (Critical for PgCat/PgBouncer) ===
net.ipv4.tcp_keepalive_time = ${NET_IPV4_TCP_KEEPALIVE_TIME:-60}
net.ipv4.tcp_keepalive_intvl = ${NET_IPV4_TCP_KEEPALIVE_INTVL:-10}
net.ipv4.tcp_keepalive_probes = ${NET_IPV4_TCP_KEEPALIVE_PROBES:-6}

# === CONGESTION CONTROL (BBR for lower latency) ===
net.core.default_qdisc = ${NET_CORE_DEFAULT_QDISC:-fq}
net.ipv4.tcp_congestion_control = ${NET_IPV4_TCP_CONGESTION_CONTROL:-bbr}

# === KERNEL ===
kernel.sched_autogroup_enabled = ${KERNEL_SCHED_AUTOGROUP_ENABLED:-0}
kernel.numa_balancing = ${KERNEL_NUMA_BALANCING:-0}
kernel.sem = ${KERNEL_SEM:-250 32000 100 128}
EOF
else
    echo "[1/5] Configuring sysctl - TCP/Network only (persistent)..."
    cat > /etc/sysctl.d/99-postgres.conf << EOF
# PgCat Proxy TCP Tuning
# Generated by 01-os-tuning.sh - DO NOT EDIT MANUALLY

# === FILE DESCRIPTORS ===
fs.file-max = ${FS_FILE_MAX:-2097152}

# === NETWORK ===
net.core.somaxconn = ${NET_CORE_SOMAXCONN:-4096}
net.core.netdev_max_backlog = ${NET_CORE_NETDEV_MAX_BACKLOG:-2048}
net.core.rmem_default = ${NET_CORE_RMEM_DEFAULT:-262144}
net.core.rmem_max = ${NET_CORE_RMEM_MAX:-16777216}
net.core.wmem_default = ${NET_CORE_WMEM_DEFAULT:-262144}
net.core.wmem_max = ${NET_CORE_WMEM_MAX:-16777216}
net.ipv4.tcp_rmem = ${NET_IPV4_TCP_RMEM:-4096 87380 16777216}
net.ipv4.tcp_wmem = ${NET_IPV4_TCP_WMEM:-4096 65536 16777216}
net.ipv4.tcp_max_syn_backlog = ${NET_IPV4_TCP_MAX_SYN_BACKLOG:-4096}
net.ipv4.tcp_tw_reuse = ${NET_IPV4_TCP_TW_REUSE:-1}
net.ipv4.tcp_fin_timeout = ${NET_IPV4_TCP_FIN_TIMEOUT:-15}

# === TCP KEEPALIVE (Critical for PgCat) ===
net.ipv4.tcp_keepalive_time = ${NET_IPV4_TCP_KEEPALIVE_TIME:-60}
net.ipv4.tcp_keepalive_intvl = ${NET_IPV4_TCP_KEEPALIVE_INTVL:-10}
net.ipv4.tcp_keepalive_probes = ${NET_IPV4_TCP_KEEPALIVE_PROBES:-6}

# === CONGESTION CONTROL (BBR for lower latency) ===
net.core.default_qdisc = ${NET_CORE_DEFAULT_QDISC:-fq}
net.ipv4.tcp_congestion_control = ${NET_IPV4_TCP_CONGESTION_CONTROL:-bbr}
EOF
fi

sysctl -p /etc/sysctl.d/99-postgres.conf

# =============================================================================
# DB NODE ONLY: HugePages, ulimits, THP
# =============================================================================
if [[ "$IS_DB_NODE" == "true" ]]; then
    # -------------------------------------------------------------------------
    # HUGEPAGES
    # -------------------------------------------------------------------------
    echo "[2/5] Configuring HugePages (persistent)..."
    NR_HUGEPAGES=${VM_NR_HUGEPAGES:-0}
    if [[ $NR_HUGEPAGES -gt 0 ]]; then
        cat > /etc/sysctl.d/99-hugepages.conf << EOF
# HugePages for PostgreSQL shared_buffers
vm.nr_hugepages = $NR_HUGEPAGES
EOF
        sysctl -p /etc/sysctl.d/99-hugepages.conf
    fi

    # -------------------------------------------------------------------------
    # ULIMITS
    # -------------------------------------------------------------------------
    echo "[3/5] Configuring ulimits (persistent)..."
    cat > /etc/security/limits.d/99-postgres.conf << EOF
# PostgreSQL user limits
* soft nofile ${ULIMIT_NOFILE:-65535}
* hard nofile ${ULIMIT_NOFILE:-65535}
* soft nproc ${ULIMIT_NPROC:-65535}
* hard nproc ${ULIMIT_NPROC:-65535}
postgres soft nofile ${ULIMIT_NOFILE:-65535}
postgres hard nofile ${ULIMIT_NOFILE:-65535}
postgres soft nproc ${ULIMIT_NPROC:-65535}
postgres hard nproc ${ULIMIT_NPROC:-65535}
EOF

    # -------------------------------------------------------------------------
    # THP - Disable Transparent Huge Pages
    # -------------------------------------------------------------------------
    echo "[4/5] Disabling Transparent Huge Pages (persistent via systemd)..."
    SERVICES_DIR="${SCRIPT_DIR}/../services"
    cp "${SERVICES_DIR}/disable-thp.service" /etc/systemd/system/disable-thp.service
    systemctl daemon-reload
    systemctl enable disable-thp.service
    systemctl start disable-thp.service 2>/dev/null || true

    # Apply immediately
    echo never > /sys/kernel/mm/transparent_hugepage/enabled 2>/dev/null || true
    echo never > /sys/kernel/mm/transparent_hugepage/defrag 2>/dev/null || true

    # -------------------------------------------------------------------------
    # PAM - Enable limits
    # -------------------------------------------------------------------------
    echo "[5/5] Ensuring PAM limits enabled..."
    if ! grep -q "pam_limits.so" /etc/pam.d/common-session 2>/dev/null; then
        echo "session required pam_limits.so" >> /etc/pam.d/common-session
    fi

    # Verification
    echo ""
    echo "=== Verification (DB Node) ==="
    echo "Persistent config files:"
    echo "  - /etc/sysctl.d/99-postgres.conf"
    echo "  - /etc/sysctl.d/99-hugepages.conf"
    echo "  - /etc/security/limits.d/99-postgres.conf"
    echo "  - /etc/systemd/system/disable-thp.service"
    echo ""
    sysctl vm.swappiness vm.dirty_ratio vm.nr_hugepages 2>/dev/null || true
    echo "THP: $(cat /sys/kernel/mm/transparent_hugepage/enabled 2>/dev/null || echo 'N/A')"
else
    # Proxy node - minimal config, just ulimits for PgCat
    echo "[2/5] Configuring ulimits for PgCat..."
    cat > /etc/security/limits.d/99-pgcat.conf << EOF
# PgCat proxy limits
* soft nofile 65535
* hard nofile 65535
ubuntu soft nofile 65535
ubuntu hard nofile 65535
EOF
    echo "[3/5] Skipping HugePages (proxy)"
    echo "[4/5] Skipping THP disable (proxy)"
    echo "[5/5] Skipping PAM config (proxy)"

    echo ""
    echo "=== Verification (Proxy Node) ==="
    echo "Persistent config files:"
    echo "  - /etc/sysctl.d/99-postgres.conf (TCP only)"
    echo "  - /etc/security/limits.d/99-pgcat.conf"
fi

echo ""
echo "=== OS Tuning Complete ==="
