#!/bin/bash
# =============================================================================
# 01-os-tuning.sh - OS Tuning with Persistence
# =============================================================================
# Applies OS tuning settings and makes them PERSISTENT across reboots.
# This is critical for snapshot recovery scenarios.
#
# Persistence locations:
#   - sysctl: /etc/sysctl.d/99-postgres.conf
#   - ulimits: /etc/security/limits.d/99-postgres.conf
#   - hugepages: /etc/sysctl.d/99-hugepages.conf
#   - THP: systemd service
#
# Usage: sudo ./01-os-tuning.sh [config.env]
# =============================================================================
set -euo pipefail

echo "=== OS Tuning with Persistence ==="

# Source config if provided
if [[ -n "${1:-}" && -f "$1" ]]; then
    echo "Loading config from: $1"
    source "$1"
fi

# =============================================================================
# SYSCTL - Memory & VM
# =============================================================================
echo "[1/5] Configuring sysctl (persistent)..."

cat > /etc/sysctl.d/99-postgres.conf << EOF
# PostgreSQL Optimized Settings
# Generated by 01-os-tuning.sh - DO NOT EDIT MANUALLY

# === MEMORY ===
vm.swappiness = ${VM_SWAPPINESS:-1}
vm.dirty_background_ratio = ${VM_DIRTY_BACKGROUND_RATIO:-1}
vm.dirty_ratio = ${VM_DIRTY_RATIO:-4}
vm.dirty_expire_centisecs = ${VM_DIRTY_EXPIRE_CENTISECS:-200}
vm.dirty_writeback_centisecs = ${VM_DIRTY_WRITEBACK_CENTISECS:-100}
vm.overcommit_memory = ${VM_OVERCOMMIT_MEMORY:-2}
vm.overcommit_ratio = ${VM_OVERCOMMIT_RATIO:-80}
vm.min_free_kbytes = ${VM_MIN_FREE_KBYTES:-335544}
vm.zone_reclaim_mode = ${VM_ZONE_RECLAIM_MODE:-0}
vm.vfs_cache_pressure = ${VM_VFS_CACHE_PRESSURE:-100}

# === FILE DESCRIPTORS ===
fs.file-max = ${FS_FILE_MAX:-2097152}
fs.aio-max-nr = ${FS_AIO_MAX_NR:-1048576}

# === NETWORK ===
net.core.somaxconn = ${NET_CORE_SOMAXCONN:-4096}
net.core.netdev_max_backlog = ${NET_CORE_NETDEV_MAX_BACKLOG:-2048}
net.core.rmem_default = ${NET_CORE_RMEM_DEFAULT:-262144}
net.core.rmem_max = ${NET_CORE_RMEM_MAX:-16777216}
net.core.wmem_default = ${NET_CORE_WMEM_DEFAULT:-262144}
net.core.wmem_max = ${NET_CORE_WMEM_MAX:-16777216}
net.ipv4.tcp_rmem = ${NET_IPV4_TCP_RMEM:-4096 87380 16777216}
net.ipv4.tcp_wmem = ${NET_IPV4_TCP_WMEM:-4096 65536 16777216}
net.ipv4.tcp_max_syn_backlog = ${NET_IPV4_TCP_MAX_SYN_BACKLOG:-4096}
net.ipv4.tcp_tw_reuse = ${NET_IPV4_TCP_TW_REUSE:-1}
net.ipv4.tcp_fin_timeout = ${NET_IPV4_TCP_FIN_TIMEOUT:-15}

# === KERNEL ===
kernel.sched_autogroup_enabled = ${KERNEL_SCHED_AUTOGROUP_ENABLED:-0}
kernel.numa_balancing = ${KERNEL_NUMA_BALANCING:-0}
kernel.sem = ${KERNEL_SEM:-250 32000 100 128}
EOF

sysctl -p /etc/sysctl.d/99-postgres.conf

# =============================================================================
# HUGEPAGES - Separate file (may need recalculation)
# =============================================================================
echo "[2/5] Configuring HugePages (persistent)..."

NR_HUGEPAGES=${VM_NR_HUGEPAGES:-0}
if [[ $NR_HUGEPAGES -gt 0 ]]; then
    cat > /etc/sysctl.d/99-hugepages.conf << EOF
# HugePages for PostgreSQL shared_buffers
vm.nr_hugepages = $NR_HUGEPAGES
EOF
    sysctl -p /etc/sysctl.d/99-hugepages.conf
fi

# =============================================================================
# ULIMITS - User limits
# =============================================================================
echo "[3/5] Configuring ulimits (persistent)..."

cat > /etc/security/limits.d/99-postgres.conf << EOF
# PostgreSQL user limits
* soft nofile ${ULIMIT_NOFILE:-65535}
* hard nofile ${ULIMIT_NOFILE:-65535}
* soft nproc ${ULIMIT_NPROC:-65535}
* hard nproc ${ULIMIT_NPROC:-65535}
postgres soft nofile ${ULIMIT_NOFILE:-65535}
postgres hard nofile ${ULIMIT_NOFILE:-65535}
postgres soft nproc ${ULIMIT_NPROC:-65535}
postgres hard nproc ${ULIMIT_NPROC:-65535}
EOF

# =============================================================================
# THP - Disable Transparent Huge Pages (systemd service for persistence)
# =============================================================================
echo "[4/5] Disabling Transparent Huge Pages (persistent via systemd)..."

cat > /etc/systemd/system/disable-thp.service << 'EOF'
[Unit]
Description=Disable Transparent Huge Pages (THP)
DefaultDependencies=no
Before=sysinit.target local-fs.target
After=local-fs.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag'
RemainAfterExit=yes

[Install]
WantedBy=basic.target
EOF

systemctl daemon-reload
systemctl enable disable-thp.service
systemctl start disable-thp.service 2>/dev/null || true

# Apply immediately
echo never > /sys/kernel/mm/transparent_hugepage/enabled 2>/dev/null || true
echo never > /sys/kernel/mm/transparent_hugepage/defrag 2>/dev/null || true

# =============================================================================
# PAM - Enable limits
# =============================================================================
echo "[5/5] Ensuring PAM limits enabled..."

if ! grep -q "pam_limits.so" /etc/pam.d/common-session 2>/dev/null; then
    echo "session required pam_limits.so" >> /etc/pam.d/common-session
fi

# =============================================================================
# VERIFICATION
# =============================================================================
echo ""
echo "=== Verification ==="
echo "Persistent config files created:"
echo "  - /etc/sysctl.d/99-postgres.conf"
echo "  - /etc/sysctl.d/99-hugepages.conf"
echo "  - /etc/security/limits.d/99-postgres.conf"
echo "  - /etc/systemd/system/disable-thp.service"
echo ""
echo "Current values:"
sysctl vm.swappiness vm.dirty_ratio vm.nr_hugepages 2>/dev/null || true
echo ""
echo "THP status:"
cat /sys/kernel/mm/transparent_hugepage/enabled 2>/dev/null || echo "N/A"
echo ""
echo "=== OS Tuning Complete (Persistent) ==="
