#!/bin/bash
# =============================================================================
# 03-disk-tuning.sh - Block Device Tuning with Persistence
# =============================================================================
# Applies block device tuning for RAID arrays and makes them PERSISTENT.
# Uses udev rules for persistence across reboots/snapshot recovery.
#
# Persistence: /etc/udev/rules.d/99-md-tuning.rules
#
# Usage: sudo ./03-disk-tuning.sh [config.env]
# =============================================================================
set -euo pipefail

echo "=== Block Device Tuning with Persistence ==="

# Source config if provided
if [[ -n "${1:-}" && -f "$1" ]]; then
    echo "Loading config from: $1"
    source "$1"
fi

# Defaults
DATA_READ_AHEAD_KB=${DATA_READ_AHEAD_KB:-64}
WAL_READ_AHEAD_KB=${WAL_READ_AHEAD_KB:-4096}
DATA_NR_REQUESTS=${DATA_NR_REQUESTS:-256}
WAL_NR_REQUESTS=${WAL_NR_REQUESTS:-128}
MD_STRIPE_CACHE_SIZE=${MD_STRIPE_CACHE_SIZE:-8192}

# =============================================================================
# UDEV RULES - Persistent block device tuning
# =============================================================================
echo "[1/3] Creating udev rules for persistent tuning..."

cat > /etc/udev/rules.d/99-md-tuning.rules << EOF
# Block device tuning for PostgreSQL RAID arrays
# Generated by 03-disk-tuning.sh - DO NOT EDIT MANUALLY

# md0 (DATA) - Optimized for random I/O (low read_ahead)
ACTION=="add|change", KERNEL=="md0", ATTR{queue/read_ahead_kb}="$DATA_READ_AHEAD_KB"
ACTION=="add|change", KERNEL=="md0", ATTR{queue/nr_requests}="$DATA_NR_REQUESTS"
ACTION=="add|change", KERNEL=="md0", ATTR{queue/add_random}="0"
ACTION=="add|change", KERNEL=="md0", ATTR{queue/rq_affinity}="2"
ACTION=="add|change", KERNEL=="md0", ATTR{md/stripe_cache_size}="$MD_STRIPE_CACHE_SIZE"

# md1 (WAL) - Optimized for sequential I/O (high read_ahead)
ACTION=="add|change", KERNEL=="md1", ATTR{queue/read_ahead_kb}="$WAL_READ_AHEAD_KB"
ACTION=="add|change", KERNEL=="md1", ATTR{queue/nr_requests}="$WAL_NR_REQUESTS"
ACTION=="add|change", KERNEL=="md1", ATTR{queue/add_random}="0"
ACTION=="add|change", KERNEL=="md1", ATTR{queue/rq_affinity}="2"
ACTION=="add|change", KERNEL=="md1", ATTR{md/stripe_cache_size}="$MD_STRIPE_CACHE_SIZE"
EOF

# =============================================================================
# SYSTEMD SERVICE - Apply tuning on boot (backup for udev)
# =============================================================================
echo "[2/3] Creating systemd service for boot-time tuning..."

cat > /etc/systemd/system/md-tuning.service << EOF
[Unit]
Description=Apply RAID block device tuning
After=local-fs.target mdmonitor.service
Wants=mdmonitor.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c '\
  [ -d /sys/block/md0 ] && echo $DATA_READ_AHEAD_KB | tee /sys/block/md0/queue/read_ahead_kb; \
  [ -d /sys/block/md0 ] && echo $DATA_NR_REQUESTS | tee /sys/block/md0/queue/nr_requests 2>/dev/null || true; \
  [ -d /sys/block/md0 ] && echo $MD_STRIPE_CACHE_SIZE | tee /sys/block/md0/md/stripe_cache_size 2>/dev/null || true; \
  [ -d /sys/block/md1 ] && echo $WAL_READ_AHEAD_KB | tee /sys/block/md1/queue/read_ahead_kb; \
  [ -d /sys/block/md1 ] && echo $WAL_NR_REQUESTS | tee /sys/block/md1/queue/nr_requests 2>/dev/null || true; \
  [ -d /sys/block/md1 ] && echo $MD_STRIPE_CACHE_SIZE | tee /sys/block/md1/md/stripe_cache_size 2>/dev/null || true; \
  echo "RAID tuning applied"'

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable md-tuning.service

# =============================================================================
# APPLY IMMEDIATELY
# =============================================================================
echo "[3/3] Applying tuning immediately..."

# md0 (DATA) - Random I/O optimized
if [[ -d /sys/block/md0 ]]; then
    blockdev --setra $((DATA_READ_AHEAD_KB * 2)) /dev/md0
    echo $DATA_NR_REQUESTS | tee /sys/block/md0/queue/nr_requests > /dev/null 2>&1 || true
    echo 0 | tee /sys/block/md0/queue/add_random > /dev/null 2>&1 || true
    echo 2 | tee /sys/block/md0/queue/rq_affinity > /dev/null 2>&1 || true
    echo $MD_STRIPE_CACHE_SIZE | tee /sys/block/md0/md/stripe_cache_size > /dev/null 2>&1 || true
    echo "  md0 (DATA): read_ahead=${DATA_READ_AHEAD_KB}KB (blockdev set)"
fi

# md1 (WAL) - Sequential I/O optimized
if [[ -d /sys/block/md1 ]]; then
    blockdev --setra $((WAL_READ_AHEAD_KB * 2)) /dev/md1
    echo $WAL_NR_REQUESTS | tee /sys/block/md1/queue/nr_requests > /dev/null 2>&1 || true
    echo 0 | tee /sys/block/md1/queue/add_random > /dev/null 2>&1 || true
    echo 2 | tee /sys/block/md1/queue/rq_affinity > /dev/null 2>&1 || true
    echo $MD_STRIPE_CACHE_SIZE | tee /sys/block/md1/md/stripe_cache_size > /dev/null 2>&1 || true
    echo "  md1 (WAL): read_ahead=${WAL_READ_AHEAD_KB}KB (blockdev set)"
fi

# =============================================================================
# VERIFICATION
# =============================================================================
echo ""
echo "=== Verification ==="
echo "Persistent config files:"
echo "  - /etc/udev/rules.d/99-md-tuning.rules"
echo "  - /etc/systemd/system/md-tuning.service"
echo ""
echo "Current values:"
for md in md0 md1; do
    if [[ -d /sys/block/$md ]]; then
        ra=$(cat /sys/block/$md/queue/read_ahead_kb 2>/dev/null || echo "N/A")
        echo "  $md: read_ahead_kb=$ra"
    fi
done
echo ""
echo "=== Block Device Tuning Complete (Persistent) ==="
