#!/bin/bash
# =============================================================================
# 04-postgres.sh - PostgreSQL Installation with Separate Data/WAL
# =============================================================================
# Installs PostgreSQL 16 with:
# - PGDATA on /data/postgresql (RAID0 DATA volume)
# - pg_wal on /wal/pg_wal (RAID0 WAL volume)
# - pg_hba.conf configured for VPC access (proxy ready)
# - User: postgres / postgres
#
# Usage: sudo ./04-postgres.sh [config.env]
# =============================================================================
set -euo pipefail

echo "=== PostgreSQL Installation ==="

# Source config if provided
if [[ -n "${1:-}" && -f "$1" ]]; then
    echo "Loading config from: $1"
    source "$1"
fi

# Defaults
PG_VERSION=${PG_VERSION:-16}
PG_DATA_DIR=${PG_DATA_DIR:-/data/postgresql}
PG_WAL_DIR=${PG_WAL_DIR:-/wal/pg_wal}
PG_LISTEN_ADDRESSES=${PG_LISTEN_ADDRESSES:-*}
PG_PORT=${PG_PORT:-5432}
PG_MAX_CONNECTIONS=${PG_MAX_CONNECTIONS:-300}
VPC_CIDR=${VPC_CIDR:-10.0.0.0/16}

# =============================================================================
# INSTALL POSTGRESQL
# =============================================================================
echo "[1/7] Installing PostgreSQL ${PG_VERSION}..."
PGO_TPC_VERSION="v1.0.10"

# Add PostgreSQL APT repository
if ! grep -q "apt.postgresql.org" /etc/apt/sources.list.d/*.list 2>/dev/null; then
    apt-get update
    apt-get install -y curl ca-certificates gnupg
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/postgresql-keyring.gpg] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
    apt-get update
fi

apt-get install -y postgresql-${PG_VERSION} postgresql-client-${PG_VERSION} postgresql-contrib-${PG_VERSION}

# =============================================================================
# STOP DEFAULT INSTANCE
# =============================================================================
echo "[2/7] Stopping default PostgreSQL instance..."
systemctl stop postgresql@${PG_VERSION}-main 2>/dev/null || true
systemctl disable postgresql@${PG_VERSION}-main 2>/dev/null || true

# =============================================================================
# CREATE DIRECTORIES
# =============================================================================
echo "[3/7] Creating data and WAL directories..."

# Create directories
mkdir -p "${PG_DATA_DIR}"
mkdir -p "${PG_WAL_DIR}"

# Set ownership
chown -R postgres:postgres "${PG_DATA_DIR}"
chown -R postgres:postgres "${PG_WAL_DIR}"
chmod 700 "${PG_DATA_DIR}"
chmod 700 "${PG_WAL_DIR}"

# =============================================================================
# INITIALIZE CLUSTER
# =============================================================================
echo "[4/7] Initializing PostgreSQL cluster..."

# Initialize with separate WAL directory
if [[ ! -f "${PG_DATA_DIR}/PG_VERSION" ]]; then
    sudo -u postgres /usr/lib/postgresql/${PG_VERSION}/bin/initdb \
        -D "${PG_DATA_DIR}" \
        --waldir="${PG_WAL_DIR}" \
        --encoding=UTF8 \
        --locale=en_US.UTF-8 \
        --data-checksums
    echo "Cluster initialized"
else
    echo "Cluster already exists"
fi

# =============================================================================
# CONFIGURE POSTGRESQL
# =============================================================================
echo "[5/7] Configuring PostgreSQL..."

# Main configuration
cat > "${PG_DATA_DIR}/postgresql.conf" << EOF
# =============================================================================
# PostgreSQL Configuration - Generated by 04-postgres.sh
# =============================================================================

# -----------------------------------------------------------------------------
# CONNECTIONS
# -----------------------------------------------------------------------------
listen_addresses = '${PG_LISTEN_ADDRESSES}'
port = ${PG_PORT}
max_connections = ${PG_MAX_CONNECTIONS}

# -----------------------------------------------------------------------------
# MEMORY (calculated from hardware)
# -----------------------------------------------------------------------------
shared_buffers = ${PG_SHARED_BUFFERS:-8GB}
effective_cache_size = ${PG_EFFECTIVE_CACHE_SIZE:-22GB}
work_mem = ${PG_WORK_MEM:-5MB}
maintenance_work_mem = ${PG_MAINTENANCE_WORK_MEM:-2GB}
huge_pages = ${PG_HUGE_PAGES:-try}

# -----------------------------------------------------------------------------
# DISK I/O
# -----------------------------------------------------------------------------
random_page_cost = ${PG_RANDOM_PAGE_COST:-1.1}
seq_page_cost = ${PG_SEQ_PAGE_COST:-1.0}
effective_io_concurrency = ${PG_EFFECTIVE_IO_CONCURRENCY:-200}

# -----------------------------------------------------------------------------
# WAL
# -----------------------------------------------------------------------------
wal_level = replica
wal_compression = ${PG_WAL_COMPRESSION:-lz4}
wal_buffers = ${PG_WAL_BUFFERS:-64MB}
max_wal_size = ${PG_MAX_WAL_SIZE:-32GB}
min_wal_size = ${PG_MIN_WAL_SIZE:-4GB}
wal_writer_delay = ${PG_WAL_WRITER_DELAY:-10ms}
wal_writer_flush_after = ${PG_WAL_WRITER_FLUSH_AFTER:-1MB}

# -----------------------------------------------------------------------------
# CHECKPOINT
# -----------------------------------------------------------------------------
checkpoint_timeout = ${PG_CHECKPOINT_TIMEOUT:-30min}
checkpoint_completion_target = ${PG_CHECKPOINT_COMPLETION_TARGET:-0.9}

# -----------------------------------------------------------------------------
# SYNC & COMMIT
# -----------------------------------------------------------------------------
synchronous_commit = ${PG_SYNCHRONOUS_COMMIT:-on}
commit_delay = ${PG_COMMIT_DELAY:-0}
commit_siblings = ${PG_COMMIT_SIBLINGS:-5}

# -----------------------------------------------------------------------------
# BACKGROUND WRITER
# -----------------------------------------------------------------------------
bgwriter_delay = ${PG_BGWRITER_DELAY:-10ms}
bgwriter_lru_multiplier = ${PG_BGWRITER_LRU_MULTIPLIER:-4.0}
bgwriter_lru_maxpages = ${PG_BGWRITER_LRU_MAXPAGES:-500}

# -----------------------------------------------------------------------------
# WORKERS
# -----------------------------------------------------------------------------
max_worker_processes = ${PG_MAX_WORKER_PROCESSES:-8}
max_parallel_workers = ${PG_MAX_PARALLEL_WORKERS:-4}
max_parallel_workers_per_gather = ${PG_MAX_PARALLEL_WORKERS_PER_GATHER:-2}

# -----------------------------------------------------------------------------
# AUTOVACUUM
# -----------------------------------------------------------------------------
autovacuum = ${PG_AUTOVACUUM:-on}
autovacuum_max_workers = ${PG_AUTOVACUUM_MAX_WORKERS:-2}
autovacuum_naptime = ${PG_AUTOVACUUM_NAPTIME:-1min}
autovacuum_vacuum_scale_factor = ${PG_AUTOVACUUM_VACUUM_SCALE_FACTOR:-0.05}
autovacuum_analyze_scale_factor = ${PG_AUTOVACUUM_ANALYZE_SCALE_FACTOR:-0.02}
autovacuum_vacuum_cost_limit = ${PG_AUTOVACUUM_VACUUM_COST_LIMIT:-10000}

# -----------------------------------------------------------------------------
# QUERY TUNING
# -----------------------------------------------------------------------------
jit = ${PG_JIT:-off}

# -----------------------------------------------------------------------------
# LOGGING
# -----------------------------------------------------------------------------
log_destination = 'stderr'
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d.log'
log_min_duration_statement = ${PG_LOG_MIN_DURATION_STATEMENT:-1000}
log_checkpoints = ${PG_LOG_CHECKPOINTS:-on}
log_lock_waits = ${PG_LOG_LOCK_WAITS:-on}
log_temp_files = 0

# -----------------------------------------------------------------------------
# STATISTICS
# -----------------------------------------------------------------------------
track_activities = on
track_counts = on
track_io_timing = on
track_wal_io_timing = on

# -----------------------------------------------------------------------------
# DYNAMIC CONFIG (from conf.d)
# -----------------------------------------------------------------------------
include_dir = 'conf.d'
EOF

# Ensure conf.d exists outside the heredoc
mkdir -p "${PG_DATA_DIR}/conf.d"
chown postgres:postgres "${PG_DATA_DIR}/conf.d"
chmod 700 "${PG_DATA_DIR}/conf.d"

# =============================================================================
# CONFIGURE PG_HBA.CONF (VPC access)
# =============================================================================
echo "[6/7] Configuring pg_hba.conf for VPC access..."

cat > "${PG_DATA_DIR}/pg_hba.conf" << EOF
# PostgreSQL Client Authentication Configuration
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections
local   all             postgres                                peer
local   all             all                                     peer

# IPv4 local connections
host    all             all             127.0.0.1/32            scram-sha-256

# VPC connections (for proxy and replicas)
host    all             all             ${VPC_CIDR}             scram-sha-256

# Replication
host    replication     all             ${VPC_CIDR}             scram-sha-256
EOF

# =============================================================================
# CREATE SYSTEMD SERVICE
# =============================================================================
cat > /etc/systemd/system/postgresql-bench.service << EOF
[Unit]
Description=PostgreSQL ${PG_VERSION} Benchmark Instance
After=network.target

[Service]
Type=forking
User=postgres
Group=postgres
Environment=PGDATA=${PG_DATA_DIR}
ExecStart=/usr/lib/postgresql/${PG_VERSION}/bin/pg_ctl start -D ${PG_DATA_DIR} -l ${PG_DATA_DIR}/log/startup.log
ExecStop=/usr/lib/postgresql/${PG_VERSION}/bin/pg_ctl stop -D ${PG_DATA_DIR} -m fast
ExecReload=/usr/lib/postgresql/${PG_VERSION}/bin/pg_ctl reload -D ${PG_DATA_DIR}
TimeoutSec=300

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable postgresql-bench

# =============================================================================
# START AND SET PASSWORD
# =============================================================================
echo "[7/7] Starting PostgreSQL and setting password..."

mkdir -p "${PG_DATA_DIR}/log"
chown postgres:postgres "${PG_DATA_DIR}/log"

systemctl start postgresql-bench

# Wait for startup
sleep 3

# Set postgres password
sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"

# Create bench database
sudo -u postgres psql -c "CREATE DATABASE bench OWNER postgres;" 2>/dev/null || true

# =============================================================================
# VERIFICATION
# =============================================================================
echo ""
echo "=== Verification ==="
echo "PostgreSQL version:"
sudo -u postgres psql -t -c "SELECT version();"

echo ""
echo "Data directory:"
ls -la "${PG_DATA_DIR}"

echo ""
echo "WAL directory:"
ls -la "${PG_WAL_DIR}"

echo ""
echo "Listening:"
ss -tlnp | grep ${PG_PORT} || true

echo ""
echo "=== PostgreSQL Installation Complete ==="
echo "Connection: psql -h localhost -U postgres -d bench"
echo "Password: postgres"
